<a href="https://colab.research.google.com/github/aomiglionni/datascience_python/blob/master/P4DS4D%3B_14%3B_Reducing_Dimensionality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SLIDE 17

In [ ]:
import numpy as np
M = np.array([[1, 3, 4], [2, 3, 5], [1, 2,
3], [5, 4, 6]])
print(M)


[[1 3 4]
 [2 3 5]
 [1 2 3]
 [5 4 6]]


SLIDE 18

In [ ]:
U, s, Vh = np.linalg.svd(M,
full_matrices=False)
print (np.shape(U),np.shape(s),np.shape(Vh))
print (s)

(4, 3) (3,) (3, 3)
[12.26362747  2.11085464  0.38436189]


SLIDE 22

In [ ]:
print (np.dot(np.dot(U, np.diag(s)), Vh)) # Full matrix reconstruction

[[1. 3. 4.]
 [2. 3. 5.]
 [1. 2. 3.]
 [5. 4. 6.]]


SLIDE 24

In [ ]:
print (np.round(np.dot(np.dot(U[:,:2],
np.diag(s[:2])), Vh[:2,:]),1)) # k=2 reconstruction

[[1.  2.8 4.1]
 [2.  3.2 4.8]
 [1.  2.  3. ]
 [5.  3.9 6. ]]


SLIDE 25

In [ ]:
print (np.round(np.dot(np.dot(U[:,:1],
np.diag(s[:1])), Vh[:1,:]),1)) # k=1 reconstruction

[[2.1 2.5 3.7]
 [2.6 3.1 4.6]
 [1.6 1.8 2.8]
 [3.7 4.3 6.5]]


SLIDE 33

In [ ]:
from sklearn.datasets import load_iris
from sklearn.decomposition import FactorAnalysis
iris = load_iris()
X, y = iris.data, iris.target
factor = FactorAnalysis(n_components=4, random_state=101).fit(X)

SLIDE 36

In [ ]:
import pandas as pd
print (pd.DataFrame(factor.components_,columns=ir
is.feature_names))

SLIDE 40

In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
pca = PCA().fit(X)
print ('Explained variance by component:
%s' % pca.explained_variance_ratio_)
print pd.DataFrame(pca.components_,columns=iris.
feature_names))

SyntaxError: ignored

SLIDE 45

In [ ]:
from sklearn.datasets import
fetch_olivetti_faces
dataset =
fetch_olivetti_faces(shuffle=True,
random_state=101)
train_faces = dataset.data[:350,:]
test_faces = dataset.data[350:,:]
train_answers = dataset.target[:350]
test_answers = dataset.target[350:]

SLIDE 48

In [ ]:
from sklearn.decomposition import
RandomizedPCA
n_components = 25
Rpca =
RandomizedPCA(n_components=n_components,
whiten=True,
random_state=101).fit(train_faces)
print 'Explained variance by %i
components: %0.3f' % (n_components,
np.sum(Rpca.explained_variance_rati
o_))
compressed_train_faces =
Rpca.transform(train_faces)
compressed_test_faces =
Rpca.transform(test_faces)

SLIDE 50

In [ ]:
import matplotlib.pyplot as plt
photo = 17 
# This is the photo in the test set we want to know about
print 'We are looking for face id=%i' 
%test_answers[photo]
plt.subplot(1, 2, 1)
plt.axis('off')
plt.title('Unknown face '+str(photo)+' in test set')
plt.imshow(test_faces[photo].reshape(64,64), cmap=plt.cm.gray,
interpolation='nearest')

SLIDE 53

In [ ]:
mask = compressed_test_faces[photo,] #Just the vector of value components of our photo
squared_errors = np.sum((compressed_train_faces -mask)**2,axis=1)
minimum_error_face = argmin(squared_errors)
most_resembling = list(np.where(squared_errors < 20)[0])
print ('Best resembling face in train test: %i' % train_answers[minimum_error_face])

SLIDE 54

In [ ]:
import matplotlib.pyplot as plt
plt.subplot(2, 2, 1)
plt.axis('off')
plt.title('Unknown face '+str(photo)+' in test set')
plt.imshow(test_faces[photo].reshape(64,64), cmap=plt.cm.gray,
interpolation='nearest')
for k,m in enumerate(most_resembling[:3]):
  plt.subplot(2, 2, 2+k)
  plt.title('Match in train set no.'+str(m))
plt.axis('off')
plt.imshow(train_faces[m].reshape(64,64), cmap=plt.cm.gray,interpolation='nearest')

plt.show()

SLIDE 59

In [ ]:
from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True,
categories = ['misc.forsale'],
remove=('headers','footers','quotes'), random_state=101)
print ('Posts: %i' % len(dataset.data))

SLIDE 61

In [ ]:
from sklearn.feature_extraction.text
import TfidfVectorizer
vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
tfidf = vectorizer.fit_transform(dataset.data)

from sklearn.decomposition import NMF
n_topics = 5
nmf = NMF(n_components=n_topics,
random_state=101).fit(tfidf)

SLIDE 64

In [ ]:
feature_names = vectorizer.get_feature_names()
n_top_words = 15
for topic_idx, topic in
  enumerate(nmf.components_):
  print ("Topic #%d:" % (topic_idx+1)),
  print (" ".join([feature_names[i]))
  for i in topic.argsort()
    [:-n_top_words - 1:-1]])

SLIDE 66

In [ ]:
print (nmf.components_[0,:].argsort()[:- n_top_words-1:-1] # Gets top words for
topic 0
[1337 1749 889 1572 2342 2263 2803 1290
2353 3615 3017 806 1022 1938 2334]

print (vectorizer.get_feature_names()[1337])
# transform indexes into words drive

SLIDE 70

In [ ]:
import pandas as pd
from scipy.sparse import csr_matrix
users = pd.read_table('ml-1m/users.dat',sep='::', header=None, names=['user_id', 'gender','age','occupation','zip'])
ratings = pd.read_table('ml1m/ratings.dat', sep='::', header=None,
names=['user_id', 'movie_id’,'rating','timestamp'])
movies = pd.read_table('ml-1m/movies.dat',
sep='::', header=None, names=['movie_id','title','genres'])
MovieLens = pd.merge(pd.merge(ratings,users), movies)

SLIDE 71

In [ ]:
ratings_mtx_df =
MovieLens.pivot_table(values='rating',
rows='user_id', cols='title',
fill_value=0)
movie_index = ratings_mtx_df.columns

SLIDE 72

In [ ]:
from sklearn.decomposition import TruncatedSVD
recom = TruncatedSVD(n_components=10, random_state=101)
R = recom.fit_transform(ratings_mtx_df.values.T)

SLIDE 73

In [ ]:
import numpy as np
correlation_matrix = np.corrcoef(R)
P = correlation_matrix[favoured_movie_idx]
print (list(movie_index[(P > 0.98) & (P < 1.0)]))