<a href="https://colab.research.google.com/github/aomiglionni/datascience_python/blob/master/P4DS4D%3B_08%3B_Operations_on_Arrays_and_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SLIDE 40

In [ ]:
import numpy as np
dataset = np.array([[2, 4, 6, 8, 3, 2, 5],[7, 5, 3, 1, 6, 8, 0],[1, 3, 2, 1, 0, 0,8]])
print np.max(dataset, axis=1) - np.min(dataset, axis=1)

SLIDE 43

In [ ]:
import numpy as np
a = np.array([15.0, 20.0, 22.0, 75.0,40.0, 35.0])
a = a*.01
print (a)

[0.15 0.2  0.22 0.75 0.4  0.35]


SLIDE 46

In [ ]:
import numpy as np
a = np.array([2, 4, 6, 8])
b = np.array([[1, 2, 3, 4],
[2, 3, 4, 5],
[3, 4, 5, 6],
[4, 5, 6, 7]])
c = np.dot(a, b)
print (c)

[ 60  80 100 120]


SLIDE 49

In [ ]:
import numpy as np
a = np.array([[2, 4, 6, 8],
[1, 3, 5, 7]])
b = np.array ([[1, 2],
[2, 3],
[3, 4],
[4, 5]])
c = np.dot(a, b)
print (c)

[[60 80]
 [50 66]]
